# -*- coding: utf-8 -*-
"""ps1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOyCPIsWqs0cSAERJGU1W_HhPYKFBpT5
"""

import math
def radius_circle(x):

 area = math.pi*x*x
 return area
x= int(input("enter the radius"))

print("area of circle",radius_circle(x))

name = input("enter the name\t")
roll = int(input("Enter the roll number\t"))
mark = int(input("enter the mark\t"))
print("NAME:", name)
print("roll:",roll)
print("mark:",mark)

list = [12, 3, 47, 10]
print('highest',max(list))

list2 = range(1,11)
for i in list2:
  j=i-1
  sum=i+j
  print('The sum of current number',i,'and previous number',j,'is',sum)

l = int(input('enter the limit'))
num=[]
for i in range(1,l+1):
  x= int(input("enter the values"))
  num.append(x)
for j in num:
  if j%5 == 0:
    print(j)

x = int(input("enter the number"))
if x > 1:
  for i in range(2,x):
     if x%i == 0:
       print("not prime")
       break
  else:
    print("prime")
else:
  print('number is zero')

l3 =[]
x= int(input("enter the range"))

for i in range(1,x+1):
   num= int(input("enter the number"))
   l3.append(num)

print(l3)
l3.reverse()
print(l3)

num = int(input("enter the range"))
for i in range(0,num):
  for j in range(0,i+1):
    print("*", end="")

  print()

list4 = []
for i in range(1,4):
 x= int(input('enter the values'))
 list4.append(x)
print(max(list4))

num = int(input('Enter the limit'))
for i in range(num):
    for j in range(i):
        print ('* ', end="")
    print('')
for i in range(num,0,-1):
    for j in range(i):
        print('* ', end="")
    print('')